
#pozenemo na zacetku, da dobimo potrebno
library(RBGL)
library(igraph)
library(ggraph)
library(networkD3)
library(shiny)
library(shinydashboard)
library(shinyjs)
library(shinyMatrix)
library(TSP)
library(pracma)
library(randomGLM)
library(googleVis)
library(colormap)
library(colortools)
library(lpSolve)
library(DiagrammeR)
library(lightsout)
library(hash)
library(eulerian)